[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
  "ignore::UserWarning:torchvision.transforms.functional_tensor",
  "ignore::DeprecationWarning:basicsr.metrics.niqe"
]
