[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
  "ignore::UserWarning:torchvision.transforms.functional_tensor",
  "ignore::DeprecationWarning:basicsr.metrics.niqe"
]
[tool.mypy]
ignore_missing_imports = true
[tool.pylint.messages_control]
disable = "missing-docstring,too-many-locals,too-many-arguments"
