name: Lint and Format Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.8.0 flake8==7.1.1 pylint==3.3.1 mypy==1.11.2 pytest==8.3.3 pytest-asyncio==0.24.0 aiogram==2.25.2 torch==1.11.0 torchvision==0.12.0 Pillow opencv-python numpy realesrgan basicsr
    - name: Run Black (format)
      run: black .
    - name: Run Black (check)
      run: black --check .
    - name: Run Flake8
      run: flake8 .
    - name: Run Pylint
      run: pylint *.py
    - name: Run Mypy
      run: mypy .
    - name: Run Pytest
      run: pytest tests/ -v
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Apply Black formatting and lint fixes [skip ci]"
          git push origin HEAD
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
